image = imread("boat.tif");
normImage = im2double(image);
base_filter=[0 0 0 0 0;1 1 1 1 1;0 0 0 0 0;-1 -1 -1 -1 -1;0 0 0 0 0]; 
angle=0; 
filter=imrotate(base_filter,angle,'crop');
filtered = imfilter(normImage, filter);
outputImage0 = filtered * 255;
figure;
subplot(3,2,1);
imshow(uint8(image));
title("Original Image");
subplot(3,2,2);
imshow(uint8(outputImage0));
title("Angle = 0 Image");
angle=45; 
filter=imrotate(base_filter,angle,'crop');
filtered = imfilter(normImage, filter);
outputImage45 = filtered * 255;
subplot(3,2,3);
imshow(uint8(outputImage45));
title("Angle = 45 Image");
angle=90; 
filter=imrotate(base_filter,angle,'crop');
filtered = imfilter(normImage, filter);
outputImage90 = filtered * 255;
subplot(3,2,4);
imshow(uint8(outputImage90));
title("Angle = 90 Image");
angle=135; 
filter=imrotate(base_filter,angle,'crop');
filtered = imfilter(normImage, filter);
outputImage135 = filtered * 255;
subplot(3,2,5);
imshow(uint8(outputImage135));
title("Angle = 135 Image");
