image = imread("two_cats.jpg");
normImage = im2double(image);
sobelHorizontal = fspecial('sobel');
sobelOutput = imfilter(normImage,sobelHorizontal); 
outputImageH = sobelOutput * 255;
figure;
subplot(2,2,1);
imshow(uint8(image));
title("Original Image");
subplot(2,2,2);
imshow(uint8(outputImageH));
title("Sobel Horizontal Image");
sobelVertical = transpose(H);
sobelOutput = imfilter(normImage,sobelVertical); 
outputImageV = sobelOutput * 255;
subplot(2,2,3);
imshow(uint8(outputImageV));
title("Sobel Vertical Image");
addH_V = abs(outputImageH) + abs(outputImageV);
subplot(2,2,4);
imshow(uint8(addH_V));
title("Added Image");
